#############################################################################
#
#  Project Name        :    Simulated MPEG DASH service
#
#  Author              :    Alex Ashley
#
#############################################################################
import dataclasses
from itertools import combinations
import logging
from pathlib import Path
from typing import Any, ClassVar, TypedDict, cast

from dashlive.drm.location import DrmLocation
from dashlive.drm.system import DrmSystem
from dashlive.server.options.drm_options import ALL_DRM_LOCATIONS, DrmSelectionTuple

FILE_START = r"""
# flake8: noqa

#############################################################################
#  Project Name        :    Simulated MPEG DASH service
#  ** This file is auto-generated. Do not edit **
#############################################################################
import logging
import unittest
from dashlive.drm.location import DrmLocation
from .mixins.check_manifest import DashManifestCheckMixin
from .mixins.flask_base import FlaskTestBase

class AutoGeneratedManifestTests(FlaskTestBase, DashManifestCheckMixin):
"""

TESTCASE = r"""
    async def {test_name}(self):
        await self.check_a_manifest_using_major_options('hand_made.mpd', {args})
"""

FILE_END = r"""

if __name__ == '__main__':
    logging.basicConfig()
    logging.getLogger().setLevel(logging.DEBUG)
    unittest.main()
"""

class AllTestOptions(TypedDict):
    mode: list[str]
    with_subs: list[bool]
    audioCodec: list[str]
    segmentTimeline: list[bool]
    useBaseUrls: list[bool]
    drmSelection: list[list[DrmSelectionTuple]|None]

@dataclasses.dataclass(slots=True)
class TestOption:
    mode: str = dataclasses.field(default='vod')
    with_subs: bool = False
    audioCodec: str = dataclasses.field(default='any')
    segmentTimeline: bool = False
    useBaseUrls: bool = False
    drmSelection: list[DrmSelectionTuple] | None = None

    def skip(self) -> bool:
        if self.drmSelection is not None:
            return self.segmentTimeline or self.useBaseUrls or self.audioCodec == 'all'
        if self.audioCodec == 'all':
            return self.segmentTimeline or self.useBaseUrls
        if self.mode == 'odvod':
            return self.segmentTimeline or self.useBaseUrls or self.with_subs
        return False

    def to_args(self) -> str:
        param_names: list[str] = [it.name for it in dataclasses.fields(self)]
        args: list[str] = []
        for name in param_names:
            value: Any = getattr(self, name)
            if name == "drmSelection":
                if value is None:
                    continue
                new_values: list[str] = []
                for drm, locations in value:
                    contents = [f"DrmLocation.{it.name}" for it in locations]
                    new_values.append(f"(\"{drm}\", {{{', '.join(contents)}}},)")
                value = f"[{', '.join(new_values)}]"
            elif isinstance(value, str):
                value = f'"{value}"'
            args.append(f"{name}={value}")
        return ', '.join(args)


class TestCaseGenerator:
    all_options: AllTestOptions

    def __init__(self) -> None:
        self.all_options = {
            "mode": ["vod", "live", "odvod"],
            "with_subs": [False, True],
            "audioCodec": ["mp4a", "ec-3", "any"],
            "segmentTimeline": [False, True],
            "useBaseUrls": [False, True],
            "drmSelection": [None]
        }
        for idx in range(1, 1 + len(DrmSystem.keys())):
            for comb in combinations(DrmSystem.values(), idx):
                sel: list[DrmSelectionTuple] = []
                for name in comb:
                    sel.append((name, ALL_DRM_LOCATIONS,))
                self.all_options["drmSelection"].append(sel)
        for name in DrmSystem.values():
            for loc in DrmLocation.all():
                self.all_options["drmSelection"].append([(name, {loc},)])
            for locs in combinations(DrmLocation.all(), 2):
                self.all_options["drmSelection"].append([(name, set(locs),)])

    def generate_tests(self, output_name: Path) -> None:
        param_names = list(self.all_options.keys())
        indexes: list[int] = [0] * len(param_names)
        done: bool = False
        num_tests: int = 0
        test_cases: list[tuple[str, str]] = []
        while not done:
            test_opt = TestOption()
            for idx, name in enumerate(param_names):
                value = self.all_options[name][indexes[idx]]
                setattr(test_opt, name, value)
            if not test_opt.skip():
                test_name: str = f"test_hand_made_{num_tests:04d}"
                test_cases.append((test_name, test_opt.to_args(),))
                num_tests += 1
            idx: int = 0
            while idx < len(param_names):
                indexes[idx] += 1
                name: str = param_names[idx]
                if indexes[idx] < len(self.all_options[name]):
                    break
                indexes[idx] = 0
                idx += 1
            if idx == len(param_names):
                done = True
        print(f"Generating Python unit test file {output_name} with {len(test_cases)} unit tests")
        with output_name.open('wt', encoding="utf-8") as dest:
            dest.write(FILE_START)
            for name, args in test_cases:
                dest.write(TESTCASE.format(test_name=name, args=args))
            dest.write(FILE_END)

    @staticmethod
    def main() -> None:
        src_dir: Path = Path(__file__).parent.parent.parent.absolute()
        output_name: Path = src_dir / "tests" / "test_auto_generated.py"
        gen = TestCaseGenerator()
        gen.generate_tests(output_name)

if __name__ == '__main__':
    logging.basicConfig()
    logging.getLogger().setLevel(logging.DEBUG)
    TestCaseGenerator.main()
