"""add stream defaults column

Revision ID: e3cdc4f4779b
Revises:
Create Date: 2023-10-01 10:08:28.861737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_jsonfield  # type: ignore


# revision identifiers, used by Alembic.
revision: str = 'e3cdc4f4779b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Stream', sa.Column('defaults', sqlalchemy_jsonfield.jsonfield.JSONField(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Stream', 'defaults')
    # ### end Alembic commands ###
