name: check JavaScript & Typescript source

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
       TZ: 'UTC'
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Use Node.js 20.14
        uses: actions/setup-node@v4
        with:
          node-version: 20.14
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: JS lint checks for legacy JavaScript code
        run: npm run lint:compat
      - name: JS lint checks of frontend code
        run: npm run lint
      - name: Unit tests of frontend code
        run: npm run coverage
